import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { Navbar } from "@/components/Navbar";
import "./globals.css";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{scrollBehavior:'smooth'}}>
      <head>
        <title>Wedraw</title>
      </head>
      <body className={nunito.className}><Navbar />{children}</body>
    </html>
  );
}
